In [1]:
import pandas as pd
data = pd.read_excel(r"C:\Users\pjayk\Documents\SP500.xlsx")

data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,17191.000000,17191.000000,17191.000000,17191.000000,17191.000000,1.719100e+04
mean,546.966024,550.229233,543.522697,547.091391,547.091391,8.945411e+08
std,643.238592,646.567762,639.645155,643.342927,643.342927,1.531001e+09
min,16.660000,16.660000,16.660000,16.660000,16.660000,6.800000e+05
25%,85.419998,86.130001,84.760002,85.424999,85.424999,8.685000e+06
50%,164.369995,165.050003,163.710007,164.289993,164.289993,8.794000e+07
75%,1073.684998,1082.705017,1065.224976,1073.669983,1073.669983,1.110950e+09
max,2867.229980,2872.870117,2851.479980,2872.870117,2872.870117,1.145623e+10

In [85]:
import pandas as pd 
import numpy as np
data = pd.read_excel(r"C:\Users\pjayk\Documents\SP500.xlsx")

data_2018 = data[
    (pd.to_datetime(data['Date']) >
        pd.to_datetime('2018-01-01')) &
    (pd.to_datetime(data['Date']) <
        pd.to_datetime('2018-12-31'))]
    
print ((data_2018))

            Date         Open         High          Low        Close  \
17110 2018-01-02  2683.729980  2695.889893  2682.360107  2695.810059
17111 2018-01-03  2697.850098  2714.370117  2697.770020  2713.060059
17112 2018-01-04  2719.310059  2729.290039  2719.070068  2723.989990
17113 2018-01-05  2731.330078  2743.449951  2727.919922  2743.149902
17114 2018-01-08  2742.669922  2748.510010  2737.600098  2747.709961
17115 2018-01-09  2751.149902  2759.139893  2747.860107  2751.290039
17116 2018-01-10  2745.550049  2750.800049  2736.060059  2748.229980
17117 2018-01-11  2752.969971  2767.560059  2752.780029  2767.560059
17118 2018-01-12  2770.179932  2787.850098  2769.639893  2786.239990
17119 2018-01-16  2798.959961  2807.540039  2768.639893  2776.419922
17120 2018-01-17  2784.989990  2807.040039  2778.379883  2802.560059
17121 2018-01-18  2802.399902  2805.830078  2792.560059  2798.030029
17122 2018-01-19  2802.600098  2810.330078  2798.080078  2810.300049
17123 2018-01-22  2809.159912  2833.030029  2808.120117  2832.969971
17124 2018-01-23  2835.050049  2842.239990  2830.590088  2839.129883
17125 2018-01-24  2845.419922  2852.969971  2824.810059  2837.540039
17126 2018-01-25  2846.239990  2848.560059  2830.939941  2839.250000
17127 2018-01-26  2847.479980  2872.870117  2846.179932  2872.870117
17128 2018-01-29  2867.229980  2870.620117  2851.479980  2853.530029
17129 2018-01-30  2832.739990  2837.750000  2818.270020  2822.429932
17130 2018-01-31  2832.409912  2839.260010  2813.040039  2823.810059
17131 2018-02-01  2816.449951  2835.959961  2812.699951  2821.979980
17132 2018-02-02  2808.919922  2808.919922  2759.969971  2762.129883
17133 2018-02-05  2741.060059  2763.389893  2638.169922  2648.939941
17134 2018-02-06  2614.780029  2701.040039  2593.070068  2695.139893
17135 2018-02-07  2690.949951  2727.669922  2681.330078  2681.659912
17136 2018-02-08  2685.010010  2685.270020  2580.560059  2581.000000
17137 2018-02-09  2601.780029  2638.669922  2532.689941  2619.550049
17138 2018-02-12  2636.750000  2672.610107  2622.449951  2656.000000
17139 2018-02-13  2646.270020  2668.840088  2637.080078  2662.939941
...          ...          ...          ...          ...          ...
17161 2018-03-16  2750.570068  2761.850098  2749.969971  2752.010010
17162 2018-03-19  2741.379883  2741.379883  2694.590088  2712.919922
17163 2018-03-20  2715.050049  2724.219971  2710.050049  2716.939941
17164 2018-03-21  2714.989990  2739.139893  2709.790039  2711.929932
17165 2018-03-22  2691.360107  2695.679932  2641.590088  2643.689941
17166 2018-03-23  2646.709961  2657.669922  2585.889893  2588.260010
17167 2018-03-26  2619.350098  2661.360107  2601.810059  2658.550049
17168 2018-03-27  2667.570068  2674.780029  2596.120117  2612.620117
17169 2018-03-28  2611.300049  2632.649902  2593.060059  2605.000000
17170 2018-03-29  2614.409912  2659.070068  2609.719971  2640.870117
17171 2018-04-02  2633.449951  2638.300049  2553.800049  2581.879883
17172 2018-04-03  2592.169922  2619.139893  2575.489990  2614.449951
17173 2018-04-04  2584.040039  2649.860107  2573.610107  2644.689941
17174 2018-04-05  2657.360107  2672.080078  2649.580078  2662.840088
17175 2018-04-06  2645.820068  2656.879883  2586.270020  2604.469971
17176 2018-04-09  2617.179932  2653.550049  2610.790039  2613.159912
17177 2018-04-10  2638.409912  2665.449951  2635.780029  2656.870117
17178 2018-04-11  2643.889893  2661.429932  2639.250000  2642.189941
17179 2018-04-12  2653.830078  2674.719971  2653.830078  2663.989990
17180 2018-04-13  2676.899902  2680.260010  2645.050049  2656.300049
17181 2018-04-16  2670.100098  2686.489990  2665.159912  2677.840088
17182 2018-04-17  2692.739990  2713.340088  2692.050049  2706.389893
17183 2018-04-18  2710.110107  2717.489990  2703.629883  2708.639893
17184 2018-04-19  2701.159912  2702.840088  2681.899902  2693.129883
17185 2018-04-20  2692.560059  2693.939941  2660.610107  2670.139893
17186 2018-04-23  2675.399902  2682.860107  2657.989990  2670.290039
17187 2018-04-24  2680.800049  2683.550049  2617.320068  2634.560059
17188 2018-04-25  2634.919922  2645.300049  2612.669922  2639.399902
17189 2018-04-26  2651.649902  2676.479980  2647.159912  2666.939941
17190 2018-04-27  2675.469971  2677.350098  2659.010010  2669.909912

         Adj Close      Volume
17110  2695.810059  3367250000
17111  2713.060059  3538660000
17112  2723.989990  3695260000
17113  2743.149902  3236620000
17114  2747.709961  3242650000
17115  2751.290039  3453480000
17116  2748.229980  3576350000
17117  2767.560059  3641320000
17118  2786.239990  3573970000
17119  2776.419922  4325970000
17120  2802.560059  3778050000
17121  2798.030029  3681470000
17122  2810.300049  3639430000
17123  2832.969971  3471780000
17124  2839.129883  3519650000
17125  2837.540039  4014070000
17126  2839.250000  3835150000
17127  2872.870117  3443230000
17128  2853.530029  3573830000
17129  2822.429932  3990650000
17130  2823.810059  4261280000
17131  2821.979980  3938450000
17132  2762.129883  4301130000
17133  2648.939941  5283460000
17134  2695.139893  5891660000
17135  2681.659912  4626570000
17136  2581.000000  5305440000
17137  2619.550049  5680070000
17138  2656.000000  4055790000
17139  2662.939941  3472870000
...            ...         ...
17161  2752.010010  5372340000
17162  2712.919922  3282130000
17163  2716.939941  3261030000
17164  2711.929932  3415510000
17165  2643.689941  3739800000
17166  2588.260010  3815080000
17167  2658.550049  3511100000
17168  2612.620117  3706350000
17169  2605.000000  3864500000
17170  2640.870117  3565990000
17171  2581.879883  3598520000
17172  2614.449951  3392810000
17173  2644.689941  3350340000
17174  2662.840088  3178970000
17175  2604.469971  3299700000
17176  2613.159912  3062960000
17177  2656.870117  3543930000
17178  2642.189941  3020760000
17179  2663.989990  3021320000
17180  2656.300049  2960910000
17181  2677.840088  3019700000
17182  2706.389893  3234360000
17183  2708.639893  3383410000
17184  2693.129883  3349370000
17185  2670.139893  3388590000
17186  2670.290039  3017480000
17187  2634.560059  3706740000
17188  2639.399902  3499440000
17189  2666.939941  3665720000
17190  2669.909912  3219030000

[81 rows x 7 columns]

ValueError: Length of values does not match length of index